force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Acronym__c.field-meta.xml
<CustomField>
    <fullName>Acronym__c</fullName>
    <label>Acronym</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DistributionCenter__c/DistributionCenter__c.object-meta.xml
<CustomObject>
    <label>Distribution Center</label>
    <nameField>
        <label>Distribution Center Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Hierarchy</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductHierarchy__c/ProductHierarchy__c.object-meta.xml
<CustomObject>
    <label>Product Hierarchy</label>
    <nameField>
        <label>Product Hierarchy Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax__c/Tax__c.object-meta.xml
<CustomObject>
    <label>Tax</label>
    <nameField>
        <label>Tax Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax__c/fields/DistributionCenter__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distribution Center</label>
    <referenceTo>DistributionCenter__c</referenceTo>
    <relationshipLabel>Taxes</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Taxes</relationshipLabel>
    <relationshipName>Taxes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax__c/fields/TaxPercentage__c.field-meta.xml
<CustomField>
    <fullName>TaxPercentage__c</fullName>
    <label>Tax Percentage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/testClasses/TaxTriggerHelper_Test.cls
@isTest
private class TaxTriggerHelper_Test {
    @TestSetup
    static void makeData(){
        TestFactorySObject testFactory = TestFactorySObject.getInstance();

        Country__c country = (Country__c) testFactory.createSObject(new Country__c());
        insert country;

        State__c state1 = (State__c) testFactory.createSObject(new State__c(Country__c = country.Id));
        State__c state2 = (State__c) testFactory.createSObject(new State__c(Country__c = country.Id));
        insert new List<State__c>{state1, state2};

        DistributionCenter__c distributionCenter = (DistributionCenter__c) testFactory.createSObject(new DistributionCenter__c());
        insert distributionCenter;

        ProductHierarchy__c productHierarchy = (ProductHierarchy__c) testFactory.createSObject(new ProductHierarchy__c());
        insert productHierarchy;

        Product2 product1 = (Product2) testFactory.createSObject(new Product2(ProductHierarchy__c = productHierarchy.Id));
        Product2 product2 = (Product2) testFactory.createSObject(new Product2(ProductHierarchy__c = productHierarchy.Id));
        insert new List<Product2>{product1, product2};

        Tax__c tax1 = (Tax__c) testFactory.createSObject(new Tax__c(
            Product__c = product1.Id,
            State__c = state1.Id,
            DistributionCenter__c = distributionCenter.Id,
            TaxPercentage__c = 10));
        
        Tax__c tax2 = (Tax__c) testFactory.createSObject(new Tax__c(
            Product__c = product2.Id,
            State__c = state2.Id,
            DistributionCenter__c = distributionCenter.Id,
            TaxPercentage__c = 12));
        
        insert new List<Tax__c>{tax1, tax2};
    }

    @isTest
    static void testInsertTwoDistinctTaxes() {
        Product2 product = [SELECT Id FROM Product2 WHERE Name = 'Product Test 5' LIMIT 1];
        State__c state = [SELECT Id FROM State__c WHERE Acronym__c = '2' LIMIT 1];
        DistributionCenter__c distributionCenter = [SELECT Id FROM DistributionCenter__c LIMIT 1];

        Tax__c tax = new Tax__c();

        tax.Product__c = product.Id;
        tax.State__c = state.Id;
        tax.DistributionCenter__c = distributionCenter.Id;
        tax.Status__c = 'Approved';
        tax.TaxPercentage__c = 15;

        Database.SaveResult result = Database.insert(tax, false);

        System.assert(result.isSuccess());
        System.assert(result.getErrors().size() == 0);
    }

    @isTest
    static void testInsertTwoDuplicateTaxes() {
        Product2 product = [SELECT Id FROM Product2 WHERE Name = 'Product Test 5' LIMIT 1];
        State__c state = [SELECT Id FROM State__c WHERE Acronym__c = '1' LIMIT 1];
        DistributionCenter__c distributionCenter = [SELECT Id FROM DistributionCenter__c LIMIT 1];

        Tax__c tax = new Tax__c();
        tax.Product__c = product.Id;
        tax.State__c = state.Id;
        tax.DistributionCenter__c = distributionCenter.Id;
        tax.TaxPercentage__c = 15;

        Database.SaveResult result = Database.insert(tax, false);

        System.assert(!result.isSuccess());
        System.assert(result.getErrors().size() > 0);
        System.assertEquals('There is already a tax for this product and state.', result.getErrors()[0].getMessage());
    }

    @isTest
    static void testUpdateIntoADuplicateTax() {
        Product2 product = [SELECT Id FROM Product2 WHERE Name = 'Product Test 5' LIMIT 1];
        State__c state = [SELECT Id FROM State__c WHERE Acronym__c = '1' LIMIT 1];
        DistributionCenter__c distributionCenter = [SELECT Id FROM DistributionCenter__c LIMIT 1];

        Tax__c tax = [SELECT Id FROM Tax__c WHERE TaxPercentage__c = 12 LIMIT 1];
        tax.Product__c = product.Id;
        tax.State__c = state.Id;
        tax.DistributionCenter__c = distributionCenter.Id;

        Database.SaveResult result = Database.update(tax, false);

        System.assert(!result.isSuccess());
        System.assert(result.getErrors().size() > 0);
        System.assertEquals('There is already a tax for this product and state.', result.getErrors()[0].getMessage());
    }
}