force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductHierarchy__c/ProductHierarchy__c.object-meta.xml
<CustomObject>
    <label>Product Hierarchy</label>
    <nameField>
        <label>Product Hierarchy Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ShippingFee__c/ShippingFee__c.object-meta.xml
<CustomObject>
    <label>Shipping Fee</label>
    <nameField>
        <label>Shipping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ShippingFee__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Shipping Fees</relationshipLabel>
    <relationshipName>Shipping_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShippingFee__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Shipping Fees</relationshipLabel>
    <relationshipName>Shipping_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShippingFee__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Shipping Fees</relationshipLabel>
    <relationshipName>Shipping_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShippingFee__c/fields/ProductHierarchy__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Hierarchy</label>
    <referenceTo>ProductHierarchy__c</referenceTo>
    <relationshipLabel>Shipping Fees</relationshipLabel>
    <relationshipName>Shipping_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShippingFee__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Shipping Fees</relationshipLabel>
    <relationshipName>Shipping_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ShippingFeeTriggerHelper.cls
public with sharing class ShippingFeeTriggerHelper {
    public static void validateNoDuplicate(List<ShippingFee__c> oldRecordList, List<ShippingFee__c> newRecordList) {
        Set<Id> selfIds = new Set<Id>();
        Set<Id> productIds = new Set<Id>();
        Set<Id> locationIds = new Set<Id>();

        for (ShippingFee__c fee : newRecordList) {
            if (fee.Product__c != null) {
                productIds.add(fee.Product__c);
            } else {
                productIds.add(fee.ProductHierarchy__c);
            }
            if (fee.City__c != null) {
                locationIds.add(fee.City__c);
            } else if (fee.State__c != null) {
                locationIds.add(fee.State__c);
            } else {
                locationIds.add(fee.Country__c);
            }
        }

        if (oldRecordList != null) {
            for (ShippingFee__c fee : oldRecordList) {
                selfIds.add(fee.Id);
            }
        }

        List<ShippingFee__c> existingFees = [SELECT Id, Product__c, ProductHierarchy__c, City__c, State__c, Country__c FROM ShippingFee__c 
            WHERE (Product__c IN :productIds OR ProductHierarchy__c IN :productIds) 
            AND (City__c IN :locationIds OR State__c IN :locationIds OR Country__c IN :locationIds)
            AND Id NOT IN :selfIds];
        if (existingFees.size() == 0) { return; }

        Map<Id, List<ShippingFee__c>> existingFeesProductMap = new Map<Id, List<ShippingFee__c>>();
        Id key;

        for (ShippingFee__c fee : existingFees) {
            if (fee.Product__c != null) {
                key = fee.Product__c;
            } else {
                key = fee.ProductHierarchy__c;
            }
            if (!existingFeesProductMap.containsKey(key)) {
                existingFeesProductMap.put(key, new List<ShippingFee__c>());
            }
            existingFeesProductMap.get(key).add(fee);
        }
        
        for (ShippingFee__c newFee : newRecordList) {
            if (newFee.Product__c != null) {
                key = newFee.Product__c;
            } else {
                key = newFee.ProductHierarchy__c;
            }
            for (ShippingFee__c existingFee : existingFeesProductMap.get(key)) {
                if (newFee.City__c == existingFee.City__c &&
                    newFee.State__c == existingFee.State__c &&
                    newFee.Country__c == existingFee.Country__c) {

                    newFee.addError('Duplicate shipping fee found.');
                }
            }
        }
    }
}